defaults: ./distillation-qwen3-32b-to-1.7b-base-1n8g-megatron-tp2pp2cp2-pack.yaml
policy:
  megatron_cfg:
    tensor_model_parallel_size: 1
teacher:
  megatron_cfg:
    tensor_model_parallel_size: 2
checkpointing:
  checkpoint_dir: checkpoints/distillation-qwen3-32b-to-1.7b-base-1n4g-megatron-tp1pp2cp2-pack
logger:
  log_dir: logs/distillation-qwen3-32b-to-1.7b-base-1n4g-megatron-tp1pp2cp2-pack
  wandb:
    name: distillation-qwen3-32b-to-1.7b-base-1n4g-megatron-tp1pp2cp2-pack
cluster:
  gpus_per_node: 4

