defaults: ./grpo-llama3.2-1b-instruct-1n8g-megatron.yaml
checkpointing:
  checkpoint_dir: results/grpo-llama3.2-1b-instruct-1n4g-megatron
logger:
  log_dir: logs/grpo-llama3.2-1b-instruct-1n4g-megatron
  wandb:
    name: grpo-llama3.2-1b-instruct-1n4g-megatron
cluster:
  gpus_per_node: 4

