defaults: ./grpo-qwen2.5-7b-instruct-4n8g-megatron.yaml
policy:
  megatron_cfg:
    tensor_model_parallel_size: 1
  make_sequence_length_divisible_by: 2
  generation:
    vllm_cfg:
      tensor_parallel_size: 2
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-7b-instruct-4n4g-megatron
logger:
  log_dir: logs/grpo-qwen2.5-7b-instruct-4n4g-megatron
  wandb:
    name: grpo-qwen2.5-7b-instruct-4n4g-megatron
cluster:
  gpus_per_node: 4

