defaults: ../../grpo_math_1B.yaml

grpo:
  max_num_steps: 450

checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1-sglang

policy:
  model_name: Qwen/Qwen2.5-Math-1.5B-Instruct
  tokenizer:
    name: Qwen/Qwen2.5-Math-1.5B-Instruct
  dynamic_batching:
    enabled: true
  sequence_packing:
    enabled: false
  make_sequence_length_divisible_by: 1
  generation:
    backend: "sglang"
    max_new_tokens: 512
    sglang_cfg:
      model_path: ${policy.model_name}
      gpus_per_server: 1
      dtype: ${policy.precision}
      context_length: 512
      allow_auto_truncate: true
      enable_memory_saver: false
      dp_size: 1
      pp_size: 1
      ep_size: 1
      max_running_requests: null
      mem_fraction_static: 0.5
      skip_server_warmup: true

data:
  max_input_seq_length: 512

logger:
  log_dir: logs/grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1-sglang
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-qwen2.5-math-1.5b-instruct-1n8g-fsdp2tp1-sglang

cluster:
  gpus_per_node: 8

