defaults: ./grpo-qwen2.5-7b-instruct-4n8g-fsdp2tp4.v3.yaml
checkpointing:
  checkpoint_dir: results/grpo-qwen2.5-7b-instruct-4n4g-fsdp2tp2
policy:
  dtensor_cfg:
    tensor_parallel_size: 2
  make_sequence_length_divisible_by: 2
  generation:
    vllm_cfg:
      tensor_parallel_size: 2
logger:
  log_dir: logs/grpo-qwen2.5-7b-instruct-4n4g-fsdp2tp2
  wandb:
    name: grpo-qwen2.5-7b-instruct-4n4g-fsdp2tp2
cluster:
  gpus_per_node: 4

