defaults: ../../sft.yaml
sft:
  max_num_steps: 350
  val_period: 20
  val_global_batch_size: 128
  val_micro_batch_size: 2
checkpointing:
  checkpoint_dir: results/sft-tmblog-llama3.1-8b-lora-megatron
  save_period: 20
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
    chat_template: default
  dtensor_cfg:
    enabled: false
  megatron_cfg:
    enabled: true
    peft:
      enabled: true
      dim: 128
      alpha: 128
    optimizer:
      lr: 2.0e-05
      min_lr: 2.0e-05
      weight_decay: 0.01 # When weight decay is set, it actually uses AdamW
      adam_eps: 1.0e-08
  train_global_batch_size: 128
  max_total_sequence_length: 4096
  make_sequence_length_divisible_by: 2
data:
  add_generation_prompt: true
  train:
    dataset_name: tulu3_sft_mixture
    split_validation_size: 0.05
    seed: ${sft.seed}
  validation: null
logger:
  log_dir: logs/sft-tmblog-llama3.1-8b
  tensorboard_enabled: false
  wandb:
    project: nemo-rl
    name: sft-tmblog-llama3.1-8b
  tensorboard:
    log_dir: tb_logs-sft-dev-tulu3
cluster:
  gpus_per_node: 8
