defaults: ../../sft.yaml
sft:
  max_num_steps: 500
checkpointing:
  checkpoint_dir: results/sft-llama3.2-1b-1n8g-fsdp2tp1
  save_period: 100
policy:
  tokenizer:
    name: meta-llama/Llama-3.2-1B
  make_sequence_length_divisible_by: 1
data:
  add_generation_prompt: true
  prompt_file: examples/prompts/math.txt
  train:
    dataset_name: OpenMathInstruct-2
    output_key: generated_solution
    split: train_1M
    seed: 42
    split_validation_size: 0.05
  validation: null
logger:
  log_dir: logs/sft-llama3.2-1b-1n8g-fsdp2tp1
  wandb:
    project: nemo-rl
    name: sft-llama3.2-1b-1n8g-fsdp2tp1
  tensorboard:
    log_dir: tb_logs-sft-dev-openmathinstruct2
cluster:
  gpus_per_node: 8
