defaults: ./sft-llama3.2-1b-1n8g-fsdp2tp1.v3.yaml
checkpointing:
  checkpoint_dir: results/sft-llama3.2-1b-1n4g-fsdp2tp1
logger:
  log_dir: logs/sft-llama3.2-1b-1n4g-fsdp2tp1
  wandb:
    name: sft-llama3.2-1b-1n4g-fsdp2tp1
cluster:
  gpus_per_node: 4

